# Run to migrate
# docker-compose exec backend ./manage.py migrate
services:
  nginx:
    build: ./nginx
    ports:
      - "8080:80"

  frontend:
    build: ./frontend
    command: sh -c "npm run build && npm install -g serve && serve -s build" 
    ports:
      - "3000:3000"

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    links:
      - db
      - redis
    environment:
      DEBUG: 0
      SECRET_KEY: ${SECRET_KEY}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}

  redis:
    image: redis

  worker:
    build:
      context: ./backend
    entrypoint: celery
    command: -A PieStore worker --loglevel=info
    environment:
      DEBUG: 0
      SECRET_KEY: ${SECRET_KEY}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./backend:/app
    links:
      - redis
    depends_on:
      # - backend
      - redis
