# Run to migrate
# docker-compose exec backend ./manage.py migrate

services:
  nginx:
    build: ./nginx
    ports:
      - "8080:80"

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/src:/app/src

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    links:
      - db
      - redis
    depends_on:
      - db
      - redis
    environment:
      DEBUG: 1
      SECRET_KEY: ${SECRET_KEY}
      POSTGRES_PASSWORD: password
      POSTGRES_USER: chef
      POSTGRES_DB: pie_store

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: chef
      POSTGRES_DB: pie_store

  redis:
    image: redis

  worker:
    build:
      context: ./backend
    entrypoint: celery
    command: -A PieStore worker --loglevel=info
    environment:
      DEBUG: 1
      SECRET_KEY: ${SECRET_KEY}
      POSTGRES_PASSWORD: password
      POSTGRES_USER: chef
      POSTGRES_DB: pie_store
    volumes:
      - ./backend:/app
    links:
      - redis
    depends_on:
      # - backend
      - redis
