# Run to migrate
# docker-compose exec backend ./manage.py migrate

services:
  nginx:
    build: ./nginx
    ports:
      - "8080:80"

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/src:/app/src

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: chef
      POSTGRES_DB: pie_store

  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: chef
      POSTGRES_DB: pie_store
