# Generated by Django 4.0.4 on 2022-05-17 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cake',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(max_length=255, verbose_name='image')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('price', models.PositiveSmallIntegerField(verbose_name='price')),
                ('description', models.TextField(verbose_name='descriptions')),
                ('creation_date', models.DateField(
                    auto_now=True, verbose_name='creation_date')),
            ],
        ),
    ]
