# Generated by Django 4.0.4 on 2022-05-21 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pie_api', '0003_cart_cartitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='item_total_price',
        ),
    ]
