# Generated by Django 4.0.4 on 2022-06-10 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pie_api', '0004_remove_cartitem_item_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='task_id',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
